package io.github.fate_grand_automata.scripts.enums

enum class MaterialEnum(val rarity: MaterialRarity = MaterialRarity.Copper) {
    Proof,
    Bone,
    Fang,
    Dust,
    Chain,
    Stinger,
    Fluid,
    Stake,
    Gunpowder,
    AmnestyBell,
    CeremonialBlade,
    UnforgettableAshes,
    ObsidianEdge,
    VestigeOfMadness,

    Seed(MaterialRarity.Silver),
    GhostLantern(MaterialRarity.Silver),
    OctupletCrystal(MaterialRarity.Silver),
    SerpentJewel(MaterialRarity.Silver),
    Feather(MaterialRarity.Silver),
    Gear(MaterialRarity.Silver),
    Page(MaterialRarity.Silver),
    HomunculusBaby(MaterialRarity.Silver),
    Horseshoe(MaterialRarity.Silver),
    Medal(MaterialRarity.Silver),
    ShellOfReminiscence(MaterialRarity.Silver),
    Magatama(MaterialRarity.Silver),
    EternalIce(MaterialRarity.Silver),
    GiantRing(MaterialRarity.Silver),
    AuroraSteel(MaterialRarity.Silver),
    SoundlessBell(MaterialRarity.Silver),
    Arrowhead(MaterialRarity.Silver),
    Tiara(MaterialRarity.Silver),
    DivineSpiritParticle(MaterialRarity.Silver),
    RainbowThreadBall(MaterialRarity.Silver),
    FantasyScales(MaterialRarity.Silver),
    Sunscale(MaterialRarity.Silver),
    Converger(MaterialRarity.Silver),

    Claw(MaterialRarity.Gold),
    Heart(MaterialRarity.Gold),
    DragonScale(MaterialRarity.Gold),
    SpiritRoot(MaterialRarity.Gold),
    YoungHorn(MaterialRarity.Gold),
    TearStone(MaterialRarity.Gold),
    Grease(MaterialRarity.Gold),
    LampOfEvilSealing(MaterialRarity.Gold),
    Scarab(MaterialRarity.Gold),
    Lanugo(MaterialRarity.Gold),
    Gallstone(MaterialRarity.Gold),
    MysteriousWine(MaterialRarity.Gold),
    ReactorCore(MaterialRarity.Gold),
    TsukumoMirror(MaterialRarity.Gold),
    EggOfTruth(MaterialRarity.Gold),
    StarShard(MaterialRarity.Gold),
    FruitOfEternity(MaterialRarity.Gold),
    DemonFlameLantern(MaterialRarity.Gold),

    MonumentSaber(MaterialRarity.Gold),
    MonumentArcher(MaterialRarity.Gold),
    MonumentLancer(MaterialRarity.Gold),
    MonumentRider(MaterialRarity.Gold),
    MonumentCaster(MaterialRarity.Gold),
    MonumentAssassin(MaterialRarity.Gold),
    MonumentBerserker(MaterialRarity.Gold),

    PieceSaber(MaterialRarity.Silver),
    PieceArcher(MaterialRarity.Silver),
    PieceLancer(MaterialRarity.Silver),
    PieceRider(MaterialRarity.Silver),
    PieceCaster(MaterialRarity.Silver),
    PieceAssassin(MaterialRarity.Silver),
    PieceBerserker(MaterialRarity.Silver),

    SkillGoldSaber(MaterialRarity.Gold),
    SkillGoldArcher(MaterialRarity.Gold),
    SkillGoldLancer(MaterialRarity.Gold),
    SkillGoldRider(MaterialRarity.Gold),
    SkillGoldCaster(MaterialRarity.Gold),
    SkillGoldAssassin(MaterialRarity.Gold),
    SkillGoldBerserker(MaterialRarity.Gold),

    SkillRedSaber(MaterialRarity.Silver),
    SkillRedArcher(MaterialRarity.Silver),
    SkillRedLancer(MaterialRarity.Silver),
    SkillRedRider(MaterialRarity.Silver),
    SkillRedCaster(MaterialRarity.Silver),
    SkillRedAssassin(MaterialRarity.Silver),
    SkillRedBerserker(MaterialRarity.Silver),

    SkillBlueSaber,
    SkillBlueArcher,
    SkillBlueLancer,
    SkillBlueRider,
    SkillBlueCaster,
    SkillBlueAssassin,
    SkillBlueBerserker,
}