package io.github.fate_grand_automata.scripts.enums

enum class MaterialEnum {
    Proof,
    Bone,
    Fang,
    Dust,
    Chain,
    Stinger,
    Fluid,
    Stake,
    Gunpowder,
    AmnestyBell,
    CeremonialBlade,
    UnforgettableAshes,
    ObsidianEdge,
    VestigeOfMadness,

    Seed,
    GhostLantern,
    OctupletCrystal,
    SerpentJewel,
    Feather,
    Gear,
    Page,
    HomunculusBaby,
    Horseshoe,
    Medal,
    ShellOfReminiscence,
    Magatama,
    EternalIce,
    GiantRing,
    AuroraSteel,
    SoundlessBell,
    Arrowhead,
    Tiara,
    DivineSpiritParticle,
    RainbowThreadBall,
    FantasyScales,
    Sunscale,
    Converger,
    FlowerOfTheEnd,
    UniversalCube,

    Claw,
    Heart,
    DragonScale,
    SpiritRoot,
    YoungHorn,
    TearStone,
    Grease,
    LampOfEvilSealing,
    Scarab,
    Lanugo,
    Gallstone,
    MysteriousWine,
    ReactorCore,
    TsukumoMirror,
    EggOfTruth,
    StarShard,
    FruitOfEternity,
    DemonFlameLantern,
    GoldenCauldron,
    MoonlightNucleus,

    MonumentSaber,
    MonumentArcher,
    MonumentLancer,
    MonumentRider,
    MonumentCaster,
    MonumentAssassin,
    MonumentBerserker,

    PieceSaber,
    PieceArcher,
    PieceLancer,
    PieceRider,
    PieceCaster,
    PieceAssassin,
    PieceBerserker,

    SkillGoldSaber,
    SkillGoldArcher,
    SkillGoldLancer,
    SkillGoldRider,
    SkillGoldCaster,
    SkillGoldAssassin,
    SkillGoldBerserker,

    SkillRedSaber,
    SkillRedArcher,
    SkillRedLancer,
    SkillRedRider,
    SkillRedCaster,
    SkillRedAssassin,
    SkillRedBerserker,

    SkillBlueSaber,
    SkillBlueArcher,
    SkillBlueLancer,
    SkillBlueRider,
    SkillBlueCaster,
    SkillBlueAssassin,
    SkillBlueBerserker,
}