package com.mathewsachin.fategrandautomata.scripts.enums

enum class MaterialEnum {
    Proof,
    Bone,
    Fang,
    Dust,
    Chain,
    Stinger,
    Fluid,
    Stake,
    Gunpowder,
    Seed,
    GhostLantern,
    OctupletCrystal,
    SerpentJewel,
    Feather,
    Gear,
    Page,
    HomunculusBaby,
    Horseshoe,
    Medal,
    ShellOfReminiscence,
    Magatama,
    EternalIce,
    GiantRing,
    AuroraSteel,

    // AncientBellOfTranquility,
    // ArrowHead,
    // CrownOfRadiantSilver,
    // DivineSpiricleVein,
    Claw,
    Heart,
    DragonScale,
    SpiritRoot,
    YoungHorn,
    TearStone,
    Grease,
    LampOfEvilSealing,
    Scarab,
    Lanugo,
    Gallstone,
    MysteriousWine,
    // DawnLightReactorCore,
    // TsukmoMirror,
    // GenesisEgg,
    // CometShard,
    // FruitOfLongevity
}