package com.mathewsachin.fategrandautomata.scripts.enums

enum class MaterialEnum {
    Proof,
    Bone,
    Fang,
    Dust,
    Chain,
    Stinger,
    Fluid,
    Stake,
    Gunpowder,
    AmnestyBell,

    Seed,
    GhostLantern,
    OctupletCrystal,
    SerpentJewel,
    Feather,
    Gear,
    Page,
    HomunculusBaby,
    Horseshoe,
    Medal,
    ShellOfReminiscence,
    Magatama,
    EternalIce,
    GiantRing,
    AuroraSteel,
    SoundlessBell,
    Arrowhead,
    Tiara,
    DivineSpiritParticle,
    RainbowThreadBall,
    FantasyScales,

    Claw,
    Heart,
    DragonScale,
    SpiritRoot,
    YoungHorn,
    TearStone,
    Grease,
    LampOfEvilSealing,
    Scarab,
    Lanugo,
    Gallstone,
    MysteriousWine,
    ReactorCore,
    TsukumoMirror,
    EggOfTruth,
    StarShard,
    FruitOfEternity,
    DemonFlameLantern,
}