name: Bug report
description: Create a report to help us improve
labels: bug

body:
  - type: checkboxes
    id: preparation
    attributes:
      label: Preparation
      description: "Before you open a bug report, you should check the following:"
      options:
        - label: I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
          required: true
        - label: I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
          required: true
        - label: I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
          required: true
  - type: dropdown
    id: server
    attributes:
      label: FGO server
      description: On which server does the problem happen?
      multiple: true
      options:
        - NA
        - JP
        - CN
        - TW
        - KR
    validations:
      required: true
  - type: input
    id: build
    attributes:
      label: FGA build number
      description: |
        The build number can be found on FGA's main screen at the top, it says BUILD:xxxx.
        
        Entering the number is enough.
      placeholder: "1023"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        
        Include steps to reproduce the error if required.
    validations:
      required: true
  - type: textarea
    id: video
    attributes:
      label: Video
      description: |
        Include a video of the script running on your device with `Debug mode` ON.
        
        ~~Recording functionality is available within the app in `More options` > `Advanced` > `Fine-tune`.~~
        Record your screen using the system recorder. Android 13 broke FGA's recording function, but the latest FGA version should be fine with the system recorder running at the same time.
        
        If the video is too large for Github, upload it to youtube.com or something similar.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Now please tell us about your device"
  - type: input
    id: device-model
    attributes:
      label: Device model
      placeholder: "Xiaomi Redmi 4"
      description: |
        The name of your phone model.
        
        If you are using an emulator, use its name and version instead.
    validations:
      required: true
  - type: dropdown
    id: android-version
    attributes:
      label: Android version
      options:
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
    validations:
      required: true
  - type: input
    id: screen-size
    attributes:
      label: Screen size
      placeholder: "1280x720"
  - type: input
    id: ram
    attributes:
      label: RAM
      placeholder: 3GB
  - type: markdown
    attributes:
      value: "If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags."
