lsi: false
baseurl: /Fate-Grand-Automata

name: Fate/Grand Automata
description: Auto-battle app for Fate/Grand Order Android
author: Mathew Sachin
url: "https://MathewSachin.github.io/Fate-Grand-Automata"

github: "https://github.com/MathewSachin/Fate-Grand-Automata"

exclude: ["Gemfile", "Gemfile.lock"]

plugins:
  - jekyll-seo-tag  # Search Engine Optimization
  - jekyll-redirect-from