name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.idea/**'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
      - 'custom-game-area/**'
      - 'FUNDING.yml'
      - 'wiki/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'
  VERSION_CODE: '${{ github.run_number }}'

jobs:
  play_store:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up JDK 17
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Determine Version Name
        shell: bash
        run: |
          VERSION_NAME=$VERSION_CODE
          echo "FGA_VERSION_CODE=$VERSION_CODE" >>${GITHUB_ENV}
          echo "FGA_VERSION_NAME=$VERSION_NAME" >>${GITHUB_ENV}

      - name: Decrypt keystore (GPG)
        env:
          GPG_KEYSTORE: ${{ secrets.GPG_KEYSTORE }}
        working-directory: ./app
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GPG_KEYSTORE" --output fgautomata.keystore fgautomata.keystore.gpg

      - uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f
        with:
          ruby-version: '4.0.2'
          bundler-cache: true

      - name: Deploy to Play Store
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7
        with:
          lane: 'deploy'
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SERVICE_ACCOUNT_NEW_APP }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}

      - name: Upload Bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: bundle
          path: app/build/outputs/bundle/release/app-release.aab
        if: ${{ !cancelled() }}

      - name: Upload De-obfuscation mapping file
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: mapping-release
          path: app/build/outputs/mapping/release/mapping.txt
        if: ${{ !cancelled() }}

      - name: Download Universal APK
        uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7
        with:
          lane: 'download_apk'
          options: '{ "version_code": "$VERSION_CODE" }'
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SERVICE_ACCOUNT_NEW_APP }}
      - name: zip APK
        run: zip FGA-apk-${VERSION_CODE}.zip *.apk
      
      - name: Create release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_CODE }}
          name: FGA ${{ env.VERSION_CODE }}
          body: |
            > [!NOTE] 
            > Use the [APKMirror Installer](https://play.google.com/store/apps/details?id=com.apkmirror.helper.prod) to install the app on Android 14+, otherwise Accessibility can't be enabled.
          files: |
            FGA-apk-${{ env.VERSION_CODE }}.zip
          generate_release_notes: true
