name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', 'mkdocs.yml', 'requirements.txt' ]
  pull_request:
    branches: [ main ]
    paths: [ 'docs/**', 'mkdocs.yml', 'requirements.txt' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Build documentation
      run: |
        mkdocs build --verbose --clean --strict
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        mkdocs gh-deploy --force