name: PR Build

on:
  pull_request_target:
    paths-ignore:
      - '.idea/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'custom-game-area/**'
      - 'wiki/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'
  VERSION_CODE: '${{ github.run_number }}'

jobs:
  build:
    runs-on: macos-latest
    permissions: 
      pull-requests: write 
    env:
      FGA_VERSION_CODE: 0
      FGA_VERSION_NAME: 0
      FGA_BUILD_NAME: ''
    steps:
      # get the PR from the event as JSON
      - uses: actions/github-script@v8
        id: pr
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.payload.pull_request.number,
            });
            return pullRequest
      
      # check out the merged result
      - uses: actions/checkout@v6
        with:
          ref: ${{fromJSON(steps.pr.outputs.result).merge_commit_sha}}

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Determine Version Name
        shell: bash
        run: |
          VERSION_NAME=$VERSION_CODE
          echo "FGA_VERSION_CODE=$VERSION_CODE" >>${GITHUB_ENV}
          echo "FGA_VERSION_NAME=$VERSION_NAME" >>${GITHUB_ENV}

      - name: Build Android Package
        run: ./gradlew assembleCi --scan --parallel --no-daemon
    
      - name: Rename Artifacts
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            build_name="${{ github.run_number }}"
          else
            build_name="${{ github.event.pull_request.number }}-build-${{ github.run_number }}"
          fi

          mv app/build/outputs/apk/ci/app-arm64-v8a-ci.apk fga-arm64-v8a-pr-$build_name.apk
          mv app/build/outputs/apk/ci/app-armeabi-v7a-ci.apk fga-armeabi-v7a-pr-$build_name.apk
          mv app/build/outputs/apk/ci/app-universal-ci.apk fga-universal-pr-$build_name.apk
          mv app/build/outputs/apk/ci/app-x86_64-ci.apk fga-x86_64-pr-$build_name.apk
          mv app/build/outputs/apk/ci/app-x86-ci.apk fga-x86-pr-$build_name.apk

          mv app/build/outputs/mapping/ci/mapping.txt fga-mapping-$build_name.txt

          echo "FGA_BUILD_NAME=$build_name" >>${GITHUB_ENV}

      - name: Upload APK
        id: upload-apk-universal
        uses: actions/upload-artifact@v6
        with:
          name: fga-pr-universal-${{ env.FGA_BUILD_NAME }}
          path: fga-universal-pr-${{ env.FGA_BUILD_NAME }}.apk
      
      - name: Upload APK (arm64-v8a)
        id: upload-apk-arm64-v8a
        uses: actions/upload-artifact@v6
        with:
          name: fga-pr-arm64-v8a-${{ env.FGA_BUILD_NAME }}
          path: fga-arm64-v8a-pr-${{ env.FGA_BUILD_NAME }}.apk

      - name: Upload APK (armeabi-v7a)
        id: upload-apk-armeabi-v7a
        uses: actions/upload-artifact@v6
        with:
          name: fga-pr-armeabi-v7a-${{ env.FGA_BUILD_NAME }}
          path: fga-armeabi-v7a-pr-${{ env.FGA_BUILD_NAME }}.apk
      
      - name: Upload APK (x86_64)
        id: upload-apk-x86_64
        uses: actions/upload-artifact@v6
        with:
          name: fga-pr-x86_64-${{ env.FGA_BUILD_NAME }}
          path: fga-x86_64-pr-${{ env.FGA_BUILD_NAME }}.apk
      
      - name: Upload APK (x86)
        id: upload-apk-x86
        uses: actions/upload-artifact@v6
        with:
          name: fga-pr-x86-${{ env.FGA_BUILD_NAME }}
          path: fga-x86-pr-${{ env.FGA_BUILD_NAME }}.apk

      - name: Upload De-obfuscation mapping file
        uses: actions/upload-artifact@v6
        with:
          name: fga-pr-mapping-${{ env.FGA_BUILD_NAME }}
          path: fga-mapping-${{ env.FGA_BUILD_NAME }}.txt
      
      - name: Comment the APK
        if: ${{ github.event_name != 'workflow_dispatch' && github.actor != 'renovate[bot]' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: apk
          message: |
            # [Build ${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Download the latest APKs for testing:
            
            Universal APK: [here](${{ steps.upload-apk-universal.outputs.artifact-url }})

            Arm64-v8a: [here](${{ steps.upload-apk-arm64-v8a.outputs.artifact-url }})

            Armeabi-v7a: [here](${{ steps.upload-apk-armeabi-v7a.outputs.artifact-url }})

            x86_64: [here](${{ steps.upload-apk-x86_64.outputs.artifact-url }})

            x86: [here](${{ steps.upload-apk-x86.outputs.artifact-url }})

            > [!NOTE] 
            > You need a GitHub account to download the APK.
            >
            > This URL is valid as long as the artifact has not expired yet.
