name: Publish wiki

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
      - '.github/workflows/publish-wiki.yml'
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: Andrew-Chen-Wang/github-wiki-action@64efa0a9436db17670a2259e0ac249d6f08bb352
